### PR TITLE
remove trailing whitespaces

### PR DESCRIPTION
**Pull request by fwolfst**
Hi Nico,

please review this first patch to remove trailing whitespaces from the "foundation" files of a new rbricks app. Note that there are still quite some files open that have similar issues (I also remember stubmling about a weird indentation somewhere). I'd be glad to clean up the erb-templates a bit if I would find time.

Have fun
Felix

### CODE REVIEW

**Comment by nicoschuele** [comment]
Hey! Thank you very much... Unfortunately, I won't be merging this PR. I wrote a script to remove trailing whitespaces everywhere and did it already. It's just not within this release of RailsBricks. I will push it to RubyGems soon.

As for the indentation, yeah, some of it is funky... Will need to have a look at that!

Have a great day.

**Comment by fwolfst** [comment]
okay, thanks god :) and thanks for all the work you put into it.

**Comment by nicoschuele** [comment]
In the controllers, I know some indentation is off too... . Will fix!

**Comment by fwolfst** [comment]
Hi Nico, will you do retabbing as well? *shudder*

**Comment by nicoschuele** [comment]
Where? Tabs are two spaces everywhere... I think.

**Comment by fwolfst** [comment]
$ rgrep --exclude-dir .git -P '\t' -l
lib/railsbricks/assets/views/pages/posts.html.erb
lib/railsbricks/assets/views/devise/devise_username/sessions/new.html.erb
lib/railsbricks/assets/views/devise/devise_email/sessions/new.html.erb
lib/railsbricks/assets/views/admin/users/devise_username/edit.html.erb
lib/railsbricks/assets/views/admin/users/devise_email/edit.html.erb
lib/railsbricks/assets/views/admin/posts/edit.html.erb
lib/railsbricks/assets/views/admin/posts/index.html.erb
lib/railsbricks/assets/views/admin/posts/_form.html.erb
lib/railsbricks/assets/views/admin/posts/drafts.html.erb
lib/railsbricks/assets/stylesheets/railsbricks_custom.scss
lib/railsbricks/foundation/app/assets/javascripts/common.js

**Comment by nicoschuele** [comment]
That's... disturbing. Will fix.

**Pull request closed without merging**
